const foodIngredients = [
    'Onion',
    'Tomato',
    'Potato',
    'Carrot',
    'Broccoli',
    'Chicken',
    'Beef',
    'Salmon',
    'Lettuce',
    'Spinach',
    'Mushroom',
    'Garlic',
    'Ginger',
    'Lemon',
    'Pasta',
    'Rice',
    'Bread',
    'Cheese',
    'Eggplant',
    'Cucumber',
    'Cabbage',
    'Avocado',
    'Pepper',
    'Zucchini',
    'Asparagus',
    'Tofu',
    'Shrimp',
    'Pineapple',
    'Strawberry',
    'Blueberry',
    'Raspberry',
    'Banana',
    'Peach',
    'Kiwi',
    'Papaya',
    'Coconut',
    'Walnut',
    'Almond',
    'Peanut',
    'Cilantro',
  'Basil',
  'Thyme',
  'Oregano',
  'Cumin',
  'Coriander',
  'Parsley',
  'Rosemary',
  'Sage',
  'Tarragon',
  'Turmeric',
  'Mustard',
  'Paprika',
  'Chili Pepper',
  'Cayenne Pepper',
  'Fennel',
  'Nutmeg',
  'Cloves',
  'Cardamom',
  'Vanilla'
  ];
  
  export default foodIngredients
  // You can use this array of food ingredients in your application as needed.
  